// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Descriptor.pb.h"
// @@protoc_insertion_point(imports)

@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBOneofDescriptorProto;
@class PBOneofDescriptorProtoBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ObjectivecDescriptorRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) objectivecFileOptions;
@end

@interface ObjectiveCFileOptions : PBGeneratedMessage {
@private
  BOOL hasPackage_:1;
  BOOL hasClassPrefix_:1;
  NSString* package;
  NSString* classPrefix;
}
- (BOOL) hasPackage;
- (BOOL) hasClassPrefix;
@property (readonly, strong) NSString* package;
@property (readonly, strong) NSString* classPrefix;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ObjectiveCFileOptionsBuilder*) builder;
+ (ObjectiveCFileOptionsBuilder*) builder;
+ (ObjectiveCFileOptionsBuilder*) builderWithPrototype:(ObjectiveCFileOptions*) prototype;
- (ObjectiveCFileOptionsBuilder*) toBuilder;

+ (ObjectiveCFileOptions*) parseFromData:(NSData*) data;
+ (ObjectiveCFileOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ObjectiveCFileOptions*) parseFromInputStream:(NSInputStream*) input;
+ (ObjectiveCFileOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ObjectiveCFileOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ObjectiveCFileOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ObjectiveCFileOptionsBuilder : PBGeneratedMessageBuilder {
@private
  ObjectiveCFileOptions* resultObjectiveCfileOptions;
}

- (ObjectiveCFileOptions*) defaultInstance;

- (ObjectiveCFileOptionsBuilder*) clear;
- (ObjectiveCFileOptionsBuilder*) clone;

- (ObjectiveCFileOptions*) build;
- (ObjectiveCFileOptions*) buildPartial;

- (ObjectiveCFileOptionsBuilder*) mergeFrom:(ObjectiveCFileOptions*) other;
- (ObjectiveCFileOptionsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ObjectiveCFileOptionsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPackage;
- (NSString*) package;
- (ObjectiveCFileOptionsBuilder*) setPackage:(NSString*) value;
- (ObjectiveCFileOptionsBuilder*) clearPackage;

- (BOOL) hasClassPrefix;
- (NSString*) classPrefix;
- (ObjectiveCFileOptionsBuilder*) setClassPrefix:(NSString*) value;
- (ObjectiveCFileOptionsBuilder*) clearClassPrefix;
@end


// @@protoc_insertion_point(global_scope)
